---
title: "Working with Vector Spatial Data in R"
format: html
---

## Setup

## Download Data

```{r}
out_dir <- here::here('data/ak_regions')

if(!dir.exists(out_dir)) {
    knb_url <- "https://dev.nceas.ucsb.edu/knb/d1/mn/v2/object/urn%3Auuid%3Aaceaecb2-1ce0-4d41-a839-d3607d32bb58"

    download.file(url = knb_url, 
                  destfile = 'shapefile_demo_data.zip', 
                  mode = 'wb')

    unzip('shapefile_demo_data.zip', exdir = out_dir)

    file.remove('shapefile_demo_data.zip')
}
```

## Attach packages

```{r}
### Data wrangling packages:
library(readr)
library(dplyr)
library(tidyr)
library(here)

### Simple Features vector spatial data:
library(sf)

### Data visualization packages:
library(ggplot2)
library(leaflet)
library(scales)
library(ggspatial)
library(prettymapr)
```


## Read in data

```{r}
ak_rgns_sf <- read_sf(here("data/ak_regions/ak_regions_simp.shp"))

##add these to gitignore
```


## Data Exploration

## Make a quick plot

```{r}
# quick plot
plot(ak_rgns_sf)

#view is not optimized for Alaska- splits it in half

```

```{r}
#what projection/datum is being used?
st_crs(ak_rgns_sf)

#transform into Alaska Albers projection which is better suited for Alaska
ak_rgns_3338_sf <- ak_rgns_sf %>%
    st_transform(crs = 3338)

# st_crs(ak_rgns_3338_sf) ### run in console to check
#now it plots the islands in the right place

class(ak_rgns_3338_sf)
head(ak_rgns_3338_sf)
```
## Download population data

```{r}
out_file <- here::here('data/alaska_population.csv')

if(!file.exists(out_file)) {
    pop_data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A7fc6f6db-c5ea-426a-a743-1f2edafb43b8"

    download.file(url = pop_data_url, 
                  destfile = out_file, 
                  mode = 'w')
}

```

#read in population data

```{r}
pop_df <- read_csv(here("data/alaska_population.csv")) %>%
    filter(Year == 2015) %>%
    select(city, lat, lng, population = total) %>%
    drop_na()

pop_4326_sf <- st_as_sf(pop_df,
                        coords = c('lng', 'lat'),
                        crs = 4326,
                        remove = FALSE)

head(pop_4326_sf)
```

#join population data with Alaska regions

```{r}
#both need to be in the same coordinate system so need to be transformed to 3338- same units and sphere
pop_3338_sf <- st_transform(pop_4326_sf, 
                            crs = 3338)

pop_joined_sf <- st_join(pop_3338_sf, 
                         ak_rgns_3338_sf, 
                         join = st_within)

head(pop_joined_sf)

#polygons merged with points -> points because we listed cities first in join, so they become points. If you switch the order, you end up with polygons instead of points
```

## Analysis

### Calculate total population by region

```{r}
pop_rgn_df <- pop_joined_sf %>%
    st_drop_geometry() %>%
    group_by(region) %>%
    summarize(total_pop = sum(population))

head(pop_rgn_df)

#Attach population summary to region sf file
pop_rgn_3338_sf <- left_join(ak_rgns_3338_sf, 
                             pop_rgn_df, 
                             by = "region")

### plot to check
plot(pop_rgn_3338_sf["total_pop"])
```


#dissolve geometries
```{r}
#Display management regions (grouping regions into those and dissolving borders) instead of just regions. Geometries will be glued together
pop_mgmt_3338_sf <- pop_rgn_3338_sf %>%
    group_by(mgmt_area) %>%
    summarize(total_pop = sum(total_pop))

plot(pop_mgmt_3338_sf["total_pop"])

#because we simplified the data we see little black dots where regions were glued together. using the orginal data would solve this
```

#save spatial object to new file


```{r}

#save it as more efficient file format than .shp- geopackage .gpkg (has some compression)
write_sf(pop_rgn_3338_sf, here("data/ak_regions_population.gpkg"))


```

## Visualization


```{r}
ggplot(pop_rgn_3338_sf) +
    geom_sf(aes(fill = total_pop)) +
    labs(fill = "Total Population") +
    scale_fill_continuous(low = "khaki", high =  "firebrick",
                          labels = comma, name = "Population") +
    theme_bw()

rivers_3338_sf <- read_sf(here("data/ak_regions/ak_rivers_simp.shp"))

#geom_sf automatically references the geometry column in your sf file

ggplot() +
    geom_sf(data = pop_rgn_3338_sf, 
            mapping = aes(fill = total_pop)) +
    geom_sf(data = rivers_3338_sf,
            aes(linewidth = StrOrder),
            color = 'blue', alpha = .5) +
    scale_linewidth(range = c(0.05, 0.5),
                    guide = "none") +
    geom_sf(data = pop_3338_sf, size = 0.5, color = 'grey20') +
    labs(title = "Total Population by Alaska Region",
         fill = "Total Population") +
    scale_fill_continuous(low = "khaki",
                          high =  "firebrick",
                          labels = comma) +
    theme_bw() 
```


#incorporate base map


```{r}
pop_3857_sf <- st_transform(pop_3338_sf, 
                         crs = 3857)

ggplot(data = pop_3857_sf) +
    ggspatial::annotation_map_tile(type = "osm", zoom = 6, progress = 'none') + 
    # higher zoom values are more detailed 
    geom_sf(aes(color = population),
            fill = NA) +
    coord_sf(xlim = c(-16900000, -16300000), ylim = c(8400000, 9000000)) +
    scale_color_continuous(low = "darkkhaki",
                           high =  "firebrick",
                           labels = comma)
```
